export const fonts = [
  {
    value: "Allura",
    label: "Allura",
  },
  {
    value: "Cookie",
    label: "Cookie",
  },
  {
    value: "Dancing Script",
    label: "Dancing Script",
  },
  {
    value: "Great Vibes",
    label: "Great Vibes",
  },
  {
    value: "Inter",
    label: "Inter",
  },
  {
    value: "Kanit",
    label: "Kanit",
  },
  {
    value: "Lato",
    label: "Lato",
  },
  {
    value: "Lora",
    label: "Lora",
  },
  {
    value: "Maven Pro",
    label: "Maven Pro",
  },
  {
    value: "Merriweather",
    label: "Merriweather",
  },
  {
    value: "Montserrat",
    label: "Montserrat",
  },
  {
    value: "Noto Sans",
    label: "Noto Sans",
  },
  {
    value: "Nunito",
    label: "Nunito",
  },
  {
    value: "Open Sans",
    label: "Open Sans",
  },
  {
    value: "Oswald",
    label: "Oswald",
  },
  {
    value: "Pacifico",
    label: "Pacifico",
  },
  {
    value: "Playfair Display",
    label: "Playfair Display",
  },
  {
    value: "Poppins",
    label: "Poppins",
  },
  {
    value: "PT Sans",
    label: "PT Sans",
  },
  {
    value: "Raleway",
    label: "Raleway",
  },
  {
    value: "Roboto",
    label: "Roboto",
  },
  {
    value: "Roboto Condensed",
    label: "Roboto Condensed",
  },
  {
    value: "Roboto Mono",
    label: "Roboto Mono",
  },
  {
    value: "Roboto Slab",
    label: "Roboto Slab",
  },
  {
    value: "Rubik",
    label: "Rubik",
  },
  {
    value: "Satisfy",
    label: "Satisfy",
  },
  {
    value: "Ubuntu",
    label: "Ubuntu",
  },
  {
    value: "Work Sans",
    label: "Work Sans",
  },
];

export const fontDeclarations = {
  Allura: {
    normal: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Allura/Allura-Regular.ttf`,
    bold: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Allura/Allura-Regular.ttf`,
    italics: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Allura/Allura-Regular.ttf`,
    bolditalics: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Allura/Allura-Regular.ttf`,
  },
  Cookie: {
    normal: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Cookie/Cookie-Regular.ttf`,
    bold: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Cookie/Cookie-Regular.ttf`,
    italics: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Cookie/Cookie-Regular.ttf`,
    bolditalics: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Cookie/Cookie-Regular.ttf`,
  },
  "Dancing Script": {
    normal: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Dancing_Script/DancingScript-Regular.ttf`,
    bold: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Dancing_Script/DancingScript-Bold.ttf`,
    italics: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Dancing_Script/DancingScript-Regular.ttf`,
    bolditalics: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Dancing_Script/DancingScript-Regular.ttf`,
  },
  "Great Vibes": {
    normal: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Great_Vibes/GreatVibes-Regular.ttf`,
    bold: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Great_Vibes/GreatVibes-Regular.ttf`,
    italics: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Great_Vibes/GreatVibes-Regular.ttf`,
    bolditalics: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Great_Vibes/GreatVibes-Regular.ttf`,
  },
  Inter: {
    normal: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Inter/Inter-Regular.ttf`,
    bold: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Inter/Inter-Bold.ttf`,
    italics: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Inter/Inter-Regular.ttf`,
    bolditalics: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Inter/Inter-Regular.ttf`,
  },
  Kanit: {
    normal: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Kanit/Kanit-Regular.ttf`,
    bold: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Kanit/Kanit-Bold.ttf`,
    italics: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Kanit/Kanit-Regular.ttf`,
    bolditalics: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Kanit/Kanit-Regular.ttf`,
  },
  Lato: {
    normal: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Lato/Lato-Regular.ttf`,
    bold: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Lato/Lato-Bold.ttf`,
    italics: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Lato/Lato-Regular.ttf`,
    bolditalics: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Lato/Lato-Regular.ttf`,
  },
  Lora: {
    normal: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Lora/Lora-Regular.ttf`,
    bold: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Lora/Lora-Bold.ttf`,
    italics: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Lora/Lora-Regular.ttf`,
    bolditalics: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Lora/Lora-Regular.ttf`,
  },
  "Maven Pro": {
    normal: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/MavenPro/MavenPro-Regular.ttf`,
    bold: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/MavenPro/MavenPro-Bold.ttf`,
    italics: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/MavenPro/MavenPro-Regular.ttf`,
    bolditalics: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/MavenPro/MavenPro-Regular.ttf`,
  },
  Merriweather: {
    normal: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Merriweather/Merriweather-Regular.ttf`,
    bold: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Merriweather/Merriweather-Bold.ttf`,
    italics: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Merriweather/Merriweather-Regular.ttf`,
    bolditalics: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Merriweather/Merriweather-Regular.ttf`,
  },
  Montserrat: {
    normal: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Montserrat/Montserrat-Regular.ttf`,
    bold: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Montserrat/Montserrat-Bold.ttf`,
    italics: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Montserrat/Montserrat-Regular.ttf`,
    bolditalics: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Montserrat/Montserrat-Regular.ttf`,
  },
  "Noto Sans": {
    normal: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Noto_Sans/NotoSans-Regular.ttf`,
    bold: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Noto_Sans/NotoSans-Bold.ttf`,
    italics: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Noto_Sans/NotoSans-Regular.ttf`,
    bolditalics: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Noto_Sans/NotoSans-Regular.ttf`,
  },
  Nunito: {
    normal: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Nunito/Nunito-Regular.ttf`,
    bold: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Nunito/Nunito-Bold.ttf`,
    italics: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Nunito/Nunito-Regular.ttf`,
    bolditalics: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Nunito/Nunito-Regular.ttf`,
  },
  "Open Sans": {
    normal: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Open_Sans/OpenSans-Regular.ttf`,
    bold: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Open_Sans/OpenSans-Bold.ttf`,
    italics: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Open_Sans/OpenSans-Regular.ttf`,
    bolditalics: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Open_Sans/OpenSans-Regular.ttf`,
  },
  Oswald: {
    normal: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Oswald/Oswald-Regular.ttf`,
    bold: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Oswald/Oswald-Bold.ttf`,
    italics: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Oswald/Oswald-Regular.ttf`,
    bolditalics: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Oswald/Oswald-Regular.ttf`,
  },
  Pacifico: {
    normal: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Pacifico/Pacifico-Regular.ttf`,
    bold: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Pacifico/Pacifico-Regular.ttf`,
    italics: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Pacifico/Pacifico-Regular.ttf`,
    bolditalics: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Pacifico/Pacifico-Regular.ttf`,
  },
  "Playfair Display": {
    normal: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Playfair_Display/PlayfairDisplay-Regular.ttf`,
    bold: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Playfair_Display/PlayfairDisplay-Bold.ttf`,
    italics: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Playfair_Display/PlayfairDisplay-Regular.ttf`,
    bolditalics: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Playfair_Display/PlayfairDisplay-Regular.ttf`,
  },
  Poppins: {
    normal: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Poppins/Poppins-Regular.ttf`,
    bold: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Poppins/Poppins-Bold.ttf`,
    italics: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Poppins/Poppins-Regular.ttf`,
    bolditalics: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Poppins/Poppins-Regular.ttf`,
  },
  "PT Sans": {
    normal: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/PT_Sans/PTSans-Regular.ttf`,
    bold: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/PT_Sans/PTSans-Bold.ttf`,
    italics: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/PT_Sans/PTSans-Regular.ttf`,
    bolditalics: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/PT_Sans/PTSans-Regular.ttf`,
  },
  Raleway: {
    normal: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Raleway/Raleway-Regular.ttf`,
    bold: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Raleway/Raleway-Bold.ttf`,
    italics: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Raleway/Raleway-Regular.ttf`,
    bolditalics: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Raleway/Raleway-Regular.ttf`,
  },
  Roboto: {
    normal: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Roboto/Roboto-Regular.ttf`,
    bold: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Roboto/Roboto-Bold.ttf`,
    italics: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Roboto/Roboto-Regular.ttf`,
    bolditalics: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Roboto/Roboto-Regular.ttf`,
  },
  "Roboto Condensed": {
    normal: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Roboto_Condensed/RobotoCondensed-Regular.ttf`,
    bold: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Roboto_Condensed/RobotoCondensed-Bold.ttf`,
    italics: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Roboto_Condensed/RobotoCondensed-Regular.ttf`,
    bolditalics: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Roboto_Condensed/RobotoCondensed-Regular.ttf`,
  },
  "Roboto Mono": {
    normal: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Roboto_Mono/RobotoMono-Regular.ttf`,
    bold: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Roboto_Mono/RobotoMono-Bold.ttf`,
    italics: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Roboto_Mono/RobotoMono-Regular.ttf`,
    bolditalics: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Roboto_Mono/RobotoMono-Regular.ttf`,
  },
  "Roboto Slab": {
    normal: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Roboto_Slab/RobotoSlab-Regular.ttf`,
    bold: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Roboto_Slab/RobotoSlab-Bold.ttf`,
    italics: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Roboto_Slab/RobotoSlab-Regular.ttf`,
    bolditalics: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Roboto_Slab/RobotoSlab-Regular.ttf`,
  },
  Rubik: {
    normal: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Rubik/Rubik-Regular.ttf`,
    bold: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Rubik/Rubik-Bold.ttf`,
    italics: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Rubik/Rubik-Regular.ttf`,
    bolditalics: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Rubik/Rubik-Regular.ttf`,
  },
  Satisfy: {
    normal: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Satisfy/Satisfy-Regular.ttf`,
    bold: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Satisfy/Satisfy-Regular.ttf`,
    italics: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Satisfy/Satisfy-Regular.ttf`,
    bolditalics: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Satisfy/Satisfy-Regular.ttf`,
  },
  Ubuntu: {
    normal: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Ubuntu/Ubuntu-Regular.ttf`,
    bold: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Ubuntu/Ubuntu-Bold.ttf`,
    italics: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Ubuntu/Ubuntu-Regular.ttf`,
    bolditalics: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Ubuntu/Ubuntu-Regular.ttf`,
  },
  "Work Sans": {
    normal: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Work_Sans/WorkSans-Regular.ttf`,
    bold: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Work_Sans/WorkSans-Bold.ttf`,
    italics: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Work_Sans/WorkSans-Regular.ttf`,
    bolditalics: `${process.env.NEXT_PUBLIC_APP_URL}/fonts/Work_Sans/WorkSans-Regular.ttf`,
  },
};

export const fontFamilies = [
  "Allura",
  "Cookie",
  "Dancing Script",
  "Great Vibes",
  "Inter",
  "Kanit",
  "Lato",
  "Lora",
  "Maven Pro",
  "Merriweather",
  "Montserrat",
  "Noto Sans",
  "Nunito",
  "Open Sans",
  "Oswald",
  "Pacifico",
  "Playfair Display",
  "Poppins",
  "PT Sans",
  "Raleway",
  "Roboto",
  "Roboto Condensed",
  "Roboto Mono",
  "Roboto Slab",
  "Rubik",
  "Satisfy",
  "Ubuntu",
  "Work Sans",
];

export const fontSizes = [
  "8",
  "9",
  "10",
  "11",
  "12",
  "13",
  "14",
  "15",
  "16",
  "17",
  "18",
  "19",
  "20",
  "21",
  "22",
  "23",
  "24",
  "25",
  "26",
  "27",
  "28",
  "29",
  "30",
  "31",
  "32",
  "36",
  "48",
  "60",
  "72",
  "96",
];
